services:
  backend:
    build: ./backend
    ports:
      - "8080"
    networks:
      - app-network
    volumes:
      - ./backend/credentials-template.json:/app/credentials-template.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials-template.json
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "5173"
    networks:
      - app-network
    depends_on:
      - backend

  database:
    image: mysql:8.3.0
    command: --default-authentication-plugin=caching_sha2_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: quizzard
      MYSQL_USER: quizzard
      MYSQL_PASSWORD: quizzard
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
