services:
  backend:
    build: ./backend
    ports:
      - "8080"
    networks:
      - app-network
    volumes:
      - ./backend/credentials.json:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000"
    networks:
      - app-network
    depends_on:
      - backend

  database:
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: melodify
      MYSQL_USER: melodify
      MYSQL_PASSWORD: melodify
    ports:
      - "3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
    ports:
      - "9200:9200"
    networks:
      - app-network
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
  


networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  elastic-data:
