name: Issue Template Form
description: General template for all issues as form
title: "Issue: "
labels: ["status: new"]
assignees:
  - 

body:
  - type: markdown
    attributes:
      value: "## Description\nThe issue description."

  - type: textarea
    attributes:
      label: Issue Description
      description: Describe the issue in detail.
      placeholder: Add a detailed description of your issue here.

  - type: checkboxes
    attributes:
      label: Tasks
      description: Mark the tasks that are to be completed.
      options:
        - label: Task 1
        - label: Task 2
        - label: Task 3

  - type: input
    attributes:
      label: Estimated Time
      description: Time estimation in minutes.
      placeholder: Enter time in minutes
      
  - type: input
    attributes:
      label: Deadline
      description: Specify the deadline for this issue.
      placeholder: "dd/mm/yyyy - Hour"

  - type: input
    attributes:
      label: Reviewer
      description: Assign a reviewer for this issue.
      placeholder: "@username - Deadline of the review (dd/mm/yyyy - hour)"
