name: Issue Template Form
description: General template for all issues as form
title: "Issue: "
labels: ["status: new"]
assignee:
  - 

body:
  - type: markdown
    attributes:
      value: "## Description\nThe issue description."

  - type: textarea
    attributes:
      label: Issue Description
      description: Describe the issue in detail.
      placeholder: Add a detailed description of your issue here.

  - type: textarea
    attributes:
      label: Tasks
      description: Edit and check off the tasks as needed.
      placeholder: |
        - [x] ~Task 1~
        - [ ] Task 2
        - [ ] Task 3

  - type: input
    attributes:
      label: Estimated Time
      description: Time estimation in minutes.
      placeholder: Enter time in minutes
      
  - type: input
    attributes:
      label: Deadline
      description: Specify the deadline for this issue.
      placeholder: "dd/mm/yyyy - Hour"

  - type: input
    attributes:
      label: Reviewer
      description: Assign a reviewer for this issue.
      placeholder: "@username - Deadline of the review (dd/mm/yyyy - hour)"
