export default {
  addListener: jest.fn(),
  removeListeners: jest.fn(),
  getValue: jest.fn(),
  setValue: jest.fn(),
  startOperationBatch: jest.fn(),
  endOperationBatch: jest.fn(),
  createAnimatedNode: jest.fn(),
  startListeningToAnimatedNodeValue: jest.fn(),
  stopListeningToAnimatedNodeValue: jest.fn(),
  connectAnimatedNodes: jest.fn(),
  disconnectAnimatedNodes: jest.fn(),
  startAnimatingNode: jest.fn(),
  stopAnimation: jest.fn(),
  setAnimatedNodeValue: jest.fn(),
  dropAnimatedNode: jest.fn(),
  extractAnimatedNodeOffset: jest.fn(),
  flattenAnimatedNodeOffset: jest.fn(),
  connectAnimatedNodeToView: jest.fn(),
  disconnectAnimatedNodeFromView: jest.fn(),
};