const mockForumPosts = [
    {
        id: 1,
        title: 'How to improve my English grammar?',
        description: 'I struggle with tenses, especially past perfect and present perfect. Any tips?',
        createdAt: new Date().toLocaleString(),
        commentCount: 8,
        tags: ['english', 'grammar', 'tenses'],
        username: 'grammar_enthusiast',
        upvotes: 15,
        hasUpvoted: true,
    },
    {
        id: 2,
        title: 'What are the best resources for learning English vocabulary?',
        description: 'I need to expand my vocabulary for professional writing.',
        createdAt: new Date().toLocaleString(),
        commentCount: 5,
        tags: ['vocabulary', 'learning'],
        username: 'wordlover123',
        upvotes: 10,
        hasUpvoted: false,
    },
    {
        id: 3,
        title: 'Difference between “affect” and “effect”?',
        description: 'I always confuse these two words. Can someone clarify?',
        createdAt: new Date().toLocaleString(),
        commentCount: 12,
        tags: ['vocabulary', 'common errors'],
        username: 'language_beginner',
        upvotes: 20,
        hasUpvoted: false,
    },
    {
        id: 4,
        title: 'How to pronounce “schedule” correctly?',
        description: 'I’ve heard both “sked-jool” and “shed-yool.” Which one is correct?',
        createdAt: new Date().toLocaleString(),
        commentCount: 6,
        tags: ['pronunciation', 'british', 'american'],
        username: 'britvsamerican',
        upvotes: 9,
        hasUpvoted: true,
    },
    {
        id: 5,
        title: 'Best techniques for practicing English speaking skills?',
        description: 'I feel shy speaking English. What are some effective practice methods?',
        createdAt: new Date().toLocaleString(),
        commentCount: 10,
        tags: ['speaking', 'confidence'],
        username: 'shy_learner',
        upvotes: 18,
        hasUpvoted: false,
    },
    {
        id: 6,
        title: 'When to use “fewer” vs “less”?',
        description: 'I’m unsure when to use “fewer” instead of “less.” Help!',
        createdAt: new Date().toLocaleString(),
        commentCount: 7,
        tags: ['grammar', 'rules'],
        username: 'grammar_seeker',
        upvotes: 13,
        hasUpvoted: false,
    },
    {
        id: 7,
        title: 'Tips for mastering English idioms?',
        description: 'Idioms are confusing. How can I learn and remember them better?',
        createdAt: new Date().toLocaleString(),
        commentCount: 9,
        tags: ['idioms', 'learning'],
        username: 'idiom_lover',
        upvotes: 16,
        hasUpvoted: true,
    },
    {
        id: 8,
        title: 'Is the Oxford comma necessary?',
        description: 'Should I always use the Oxford comma in my writing?',
        createdAt: new Date().toLocaleString(),
        commentCount: 4,
        tags: ['writing', 'grammar'],
        username: 'punctuation_fanatic',
        upvotes: 11,
        hasUpvoted: false,
    },
    {
        id: 9,
        title: 'What’s the difference between British and American spelling?',
        description: 'Why are there different spellings for some words, like “colour” and “color”?',
        createdAt: new Date().toLocaleString(),
        commentCount: 5,
        tags: ['british', 'american', 'spelling'],
        username: 'spelling_geek',
        upvotes: 14,
        hasUpvoted: true,
    },
    {
        id: 10,
        title: 'Best podcasts for improving English listening skills?',
        description: 'Looking for recommendations for podcasts to improve my English listening.',
        createdAt: new Date().toLocaleString(),
        commentCount: 8,
        tags: ['listening', 'resources'],
        username: 'audio_learner',
        upvotes: 17,
        hasUpvoted: true,
    },
];
